### ISSUE TITLE
老哥ss来的

### ISSUE THREAD

**Issue by ztdf123** [deximy/FxxkCiDaRen#5]
大佬，今天脚本不能用了.
能帮忙分析下什么原因吗
我自己研究了半天没太搞懂，毕竟前面没研究。。
submitanswer函数这一行代码出的问题
result_object = json.loads(response.text)
我打开看了一眼，不知道原来的response.text是什么，现在是这个样子
![image](https://user-images.githubusercontent.com/44315256/111267665-38f0f100-8667-11eb-9ed3-92cce88c245e.png)
`[Tue Mar 16 13:02:05 2021]  Traceback (most recent call last):
  File "d:/202003/gycss/fxk - 副本.py", line 365, in Start
    if SubmitAnswer(BuildAnswerObject(GetQuestionDetail(question_list[i], header)), header):
  File "d:/202003/gycss/fxk - 副本.py", line 288, in SubmitAnswer
    result_object = json.loads(response.text)
  File "C:\Users\辰\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\辰\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\辰\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
我也不知道为什么，猜想是原来有json的数据可以解析，现在没有了。
然后我再那个页面里找到的明文md5的值，answer里没有，不知道是什么。
能不能加个QQ一起交流下，不为了分，主要是想咨询大佬问题，可以的话，谢谢了。
- 936137610
我想着电脑模拟微信浏览器来着，研究了半天好像同时需要ua和cookie，弄完网页端的脚本也挂了，还不如研究下这个爬虫怎么挂了，哈哈。

**Comment by deximy** [comment]
四史死掉就让它死掉吧，累了。

你发的这个页面应该是被检测到了之后返回了个空页面，乱码是因为编码不对。

MD5是我自己算出来的，储存明文太占空间。
